# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Wed Dec 11 23:29:00 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1013, 894)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Orthogonality = QtGui.QTabWidget(self.centralwidget)
        self.Orthogonality.setGeometry(QtCore.QRect(0, 10, 1011, 861))
        self.Orthogonality.setObjectName("Orthogonality")
        self.Orthogonality1 = QtGui.QWidget()
        self.Orthogonality1.setObjectName("Orthogonality1")
        self.label_5 = QtGui.QLabel(self.Orthogonality1)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_5.setObjectName("label_5")
        self.orthogonality_m = QtGui.QSlider(self.Orthogonality1)
        self.orthogonality_m.setGeometry(QtCore.QRect(10, 30, 160, 22))
        self.orthogonality_m.setMaximum(5)
        self.orthogonality_m.setOrientation(QtCore.Qt.Horizontal)
        self.orthogonality_m.setTickPosition(QtGui.QSlider.TicksBelow)
        self.orthogonality_m.setTickInterval(1)
        self.orthogonality_m.setObjectName("orthogonality_m")
        self.m_label = QtGui.QLabel(self.Orthogonality1)
        self.m_label.setGeometry(QtCore.QRect(10, 60, 46, 13))
        self.m_label.setObjectName("m_label")
        self.integral_text = QtGui.QTextBrowser(self.Orthogonality1)
        self.integral_text.setGeometry(QtCore.QRect(10, 190, 281, 141))
        self.integral_text.setObjectName("integral_text")
        self.inner_product_box = QtGui.QGroupBox(self.Orthogonality1)
        self.inner_product_box.setGeometry(QtCore.QRect(10, 80, 281, 101))
        self.inner_product_box.setObjectName("inner_product_box")
        self.label_6 = QtGui.QLabel(self.inner_product_box)
        self.label_6.setGeometry(QtCore.QRect(10, 30, 181, 16))
        self.label_6.setObjectName("label_6")
        self.psi_psi = QtGui.QRadioButton(self.inner_product_box)
        self.psi_psi.setGeometry(QtCore.QRect(10, 60, 102, 20))
        self.psi_psi.setObjectName("psi_psi")
        self.psi_phi = QtGui.QRadioButton(self.inner_product_box)
        self.psi_phi.setGeometry(QtCore.QRect(90, 60, 102, 20))
        self.psi_phi.setObjectName("psi_phi")
        self.phi_phi = QtGui.QRadioButton(self.inner_product_box)
        self.phi_phi.setGeometry(QtCore.QRect(170, 60, 102, 20))
        self.phi_phi.setObjectName("phi_phi")
        self.orth_webView = QtWebKit.QWebView(self.Orthogonality1)
        self.orth_webView.setGeometry(QtCore.QRect(310, 10, 681, 811))
        self.orth_webView.setUrl(QtCore.QUrl("about:blank"))
        self.orth_webView.setObjectName("orth_webView")
        self.Orthogonality.addTab(self.Orthogonality1, "")
        self.fourier_series_tab = QtGui.QWidget()
        self.fourier_series_tab.setObjectName("fourier_series_tab")
        self.layoutWidget = QtGui.QWidget(self.fourier_series_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 278, 332))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.function_selector = QtGui.QComboBox(self.layoutWidget)
        self.function_selector.setObjectName("function_selector")
        self.function_selector.addItem("")
        self.function_selector.addItem("")
        self.function_selector.addItem("")
        self.verticalLayout.addWidget(self.function_selector)
        self.fs_checkbox = QtGui.QCheckBox(self.layoutWidget)
        self.fs_checkbox.setObjectName("fs_checkbox")
        self.verticalLayout.addWidget(self.fs_checkbox)
        self.integral_checkbox = QtGui.QCheckBox(self.layoutWidget)
        self.integral_checkbox.setObjectName("integral_checkbox")
        self.verticalLayout.addWidget(self.integral_checkbox)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.number_of_terms = QtGui.QSlider(self.layoutWidget)
        self.number_of_terms.setMinimum(1)
        self.number_of_terms.setMaximum(100)
        self.number_of_terms.setOrientation(QtCore.Qt.Horizontal)
        self.number_of_terms.setTickPosition(QtGui.QSlider.TicksBelow)
        self.number_of_terms.setTickInterval(10)
        self.number_of_terms.setObjectName("number_of_terms")
        self.verticalLayout.addWidget(self.number_of_terms)
        self.number_of_terms_label = QtGui.QLabel(self.layoutWidget)
        self.number_of_terms_label.setObjectName("number_of_terms_label")
        self.verticalLayout.addWidget(self.number_of_terms_label)
        self.save_group = QtGui.QGroupBox(self.layoutWidget)
        self.save_group.setObjectName("save_group")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.save_group)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtGui.QLabel(self.save_group)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.filename = QtGui.QLineEdit(self.save_group)
        self.filename.setObjectName("filename")
        self.verticalLayout_3.addWidget(self.filename)
        self.save = QtGui.QPushButton(self.save_group)
        self.save.setObjectName("save")
        self.verticalLayout_3.addWidget(self.save)
        self.validation = QtGui.QLabel(self.save_group)
        self.validation.setText("")
        self.validation.setObjectName("validation")
        self.verticalLayout_3.addWidget(self.validation)
        self.verticalLayout.addWidget(self.save_group)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.widget = QtGui.QWidget(self.fourier_series_tab)
        self.widget.setGeometry(QtCore.QRect(300, 10, 691, 451))
        self.widget.setObjectName("widget")
        self.fourier_webView = QtWebKit.QWebView(self.fourier_series_tab)
        self.fourier_webView.setGeometry(QtCore.QRect(10, 470, 981, 351))
        self.fourier_webView.setUrl(QtCore.QUrl("about:blank"))
        self.fourier_webView.setObjectName("fourier_webView")
        self.Orthogonality.addTab(self.fourier_series_tab, "")
        self.gibbs_tab = QtGui.QWidget()
        self.gibbs_tab.setObjectName("gibbs_tab")
        self.gibbs_widget = QtGui.QWidget(self.gibbs_tab)
        self.gibbs_widget.setGeometry(QtCore.QRect(320, 10, 651, 351))
        self.gibbs_widget.setObjectName("gibbs_widget")
        self.Orthogonality.addTab(self.gibbs_tab, "")
        self.par_tab = QtGui.QWidget()
        self.par_tab.setObjectName("par_tab")
        self.par_widget = QtGui.QWidget(self.par_tab)
        self.par_widget.setGeometry(QtCore.QRect(320, 10, 671, 501))
        self.par_widget.setObjectName("par_widget")
        self.label_3 = QtGui.QLabel(self.par_tab)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 251, 16))
        self.label_3.setObjectName("label_3")
        self.number_of_terms_pi = QtGui.QSlider(self.par_tab)
        self.number_of_terms_pi.setGeometry(QtCore.QRect(10, 40, 160, 22))
        self.number_of_terms_pi.setMinimum(1)
        self.number_of_terms_pi.setMaximum(300)
        self.number_of_terms_pi.setOrientation(QtCore.Qt.Horizontal)
        self.number_of_terms_pi.setTickPosition(QtGui.QSlider.TicksBelow)
        self.number_of_terms_pi.setTickInterval(30)
        self.number_of_terms_pi.setObjectName("number_of_terms_pi")
        self.number_n_pi = QtGui.QLabel(self.par_tab)
        self.number_n_pi.setGeometry(QtCore.QRect(10, 80, 46, 13))
        self.number_n_pi.setObjectName("number_n_pi")
        self.computed_pi = QtGui.QLabel(self.par_tab)
        self.computed_pi.setGeometry(QtCore.QRect(10, 110, 271, 81))
        self.computed_pi.setText("")
        self.computed_pi.setObjectName("computed_pi")
        self.parseval_webView = QtWebKit.QWebView(self.par_tab)
        self.parseval_webView.setGeometry(QtCore.QRect(10, 520, 981, 301))
        self.parseval_webView.setUrl(QtCore.QUrl("about:blank"))
        self.parseval_webView.setObjectName("parseval_webView")
        self.save_group_2 = QtGui.QGroupBox(self.par_tab)
        self.save_group_2.setEnabled(True)
        self.save_group_2.setGeometry(QtCore.QRect(10, 200, 272, 120))
        self.save_group_2.setObjectName("save_group_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.save_group_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtGui.QLabel(self.save_group_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.parseval_filename = QtGui.QLineEdit(self.save_group_2)
        self.parseval_filename.setObjectName("parseval_filename")
        self.verticalLayout_5.addWidget(self.parseval_filename)
        self.parseval_save = QtGui.QPushButton(self.save_group_2)
        self.parseval_save.setObjectName("parseval_save")
        self.verticalLayout_5.addWidget(self.parseval_save)
        self.parseval_validation = QtGui.QLabel(self.save_group_2)
        self.parseval_validation.setText("")
        self.parseval_validation.setObjectName("parseval_validation")
        self.verticalLayout_5.addWidget(self.parseval_validation)
        self.Orthogonality.addTab(self.par_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1013, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Orthogonality.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Please pick a value for m:", None, QtGui.QApplication.UnicodeUTF8))
        self.orthogonality_m.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>The index number you would like to take the inner product of the function with.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.m_label.setText(QtGui.QApplication.translate("MainWindow", "m = 0", None, QtGui.QApplication.UnicodeUTF8))
        self.integral_text.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>The computed orthogonality relations.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.inner_product_box.setTitle(QtGui.QApplication.translate("MainWindow", "Inner product", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Calculate orthogonality for:", None, QtGui.QApplication.UnicodeUTF8))
        self.psi_psi.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Take the inner product of psi * psi.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.psi_psi.setText(QtGui.QApplication.translate("MainWindow", "Psi * Psi", None, QtGui.QApplication.UnicodeUTF8))
        self.psi_phi.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Takes the inner product of psi * phi.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.psi_phi.setText(QtGui.QApplication.translate("MainWindow", "Psi * Phi", None, QtGui.QApplication.UnicodeUTF8))
        self.phi_phi.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Takes the inner product of phi * phi.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.phi_phi.setText(QtGui.QApplication.translate("MainWindow", "Phi * Phi", None, QtGui.QApplication.UnicodeUTF8))
        self.Orthogonality.setTabText(self.Orthogonality.indexOf(self.Orthogonality1), QtGui.QApplication.translate("MainWindow", "Orthogonality", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Please select a function:", None, QtGui.QApplication.UnicodeUTF8))
        self.function_selector.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>This is the function that you would like to be approximated using a Fourier series.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.function_selector.setItemText(0, QtGui.QApplication.translate("MainWindow", "Triangle wave", None, QtGui.QApplication.UnicodeUTF8))
        self.function_selector.setItemText(1, QtGui.QApplication.translate("MainWindow", "Square wave", None, QtGui.QApplication.UnicodeUTF8))
        self.function_selector.setItemText(2, QtGui.QApplication.translate("MainWindow", "Saw tooth wave", None, QtGui.QApplication.UnicodeUTF8))
        self.fs_checkbox.setText(QtGui.QApplication.translate("MainWindow", "Include Fourier approximation", None, QtGui.QApplication.UnicodeUTF8))
        self.integral_checkbox.setText(QtGui.QApplication.translate("MainWindow", "Calculate integrals numerically", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Please select the number of terms to use:", None, QtGui.QApplication.UnicodeUTF8))
        self.number_of_terms.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>This is the number of terms you would like to approximate the function with.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.number_of_terms_label.setText(QtGui.QApplication.translate("MainWindow", "n = 1", None, QtGui.QApplication.UnicodeUTF8))
        self.save_group.setTitle(QtGui.QApplication.translate("MainWindow", "Save plot as file", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Filename:", None, QtGui.QApplication.UnicodeUTF8))
        self.filename.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>The name of the file that you want to be saved.  If left blank the file will be saved as: &lt;function_name&gt;_&lt;number_of_terms&gt;.eps.</p><p><br/></p><p>Alphanumeric characters only!</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.save.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>This saves the image with the specified file name in the &quot;user_images&quot; folder located in the same directory as this python script.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.save.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.Orthogonality.setTabText(self.Orthogonality.indexOf(self.fourier_series_tab), QtGui.QApplication.translate("MainWindow", "Fourier series ", None, QtGui.QApplication.UnicodeUTF8))
        self.Orthogonality.setTabText(self.Orthogonality.indexOf(self.gibbs_tab), QtGui.QApplication.translate("MainWindow", "The Gibbs Phenomenon", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "How many terms should be used to approximate pi:", None, QtGui.QApplication.UnicodeUTF8))
        self.number_of_terms_pi.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>The number of terms that the algorithm will use to calculate pi with.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.number_n_pi.setText(QtGui.QApplication.translate("MainWindow", "n=1", None, QtGui.QApplication.UnicodeUTF8))
        self.save_group_2.setTitle(QtGui.QApplication.translate("MainWindow", "Save plot as file", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Filename:", None, QtGui.QApplication.UnicodeUTF8))
        self.parseval_filename.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>The name of the file that you want to be saved.  If left blank the file will be saved as: &lt;function_name&gt;_&lt;number_of_terms&gt;.eps.</p><p><br/></p><p>Alphanumeric characters only!</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.parseval_save.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>This saves the image with the specified file name in the &quot;user_images&quot; folder located in the same directory as this python script.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.parseval_save.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.Orthogonality.setTabText(self.Orthogonality.indexOf(self.par_tab), QtGui.QApplication.translate("MainWindow", "Parseval\'s Theorem", None, QtGui.QApplication.UnicodeUTF8))

from PySide import QtWebKit
